/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parentpoint.ds;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import parentpoint.koneksi.koneksi;
import parentpoint.LOGIN.LOGIN;
import parentpoint.report.report;

/**
 *
 * @author HP
 */
public class dsmainframe extends javax.swing.JFrame {

    /**
     * Creates new form dsmainframe
     */
    public dsmainframe() {
        initComponents();
        setTitle("PARENT POINT - Dashboard Utama");
        setLocationRelativeTo(null);
        
        // Action untuk tombol Dashboard
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds dashboard = new ds();
                dashboard.setVisible(true);
                dashboard.setLocationRelativeTo(null);
            }
        });
        
        // Action untuk tombol Data Siswa
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataSiswa();
            }
        });
        
        // Action untuk tombol Data Orang Tua
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataOrangTua();
            }
        });
        
        // Action untuk tombol Data Kelas
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataKelas();
            }
        });
        
        // Action untuk tombol Kehadiran
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOptionPane.showMessageDialog(null, "Fitur Input Kehadiran akan segera tersedia.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        });
        
        // Action untuk tombol Laporan Kehadiran
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report rpt = new report();
                rpt.setVisible(true);
                rpt.setLocationRelativeTo(null);
            }
        });
        
        // Action untuk tombol Manajemen User
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilManajemenUser();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.setActionCommand("0,5");
        jButton1.setAlignmentX(15.0F);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton2.setText("Data Siswa");
        jButton2.setActionCommand("0,5");
        jButton2.setAlignmentX(15.0F);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton3.setText("Data Orang Tua ");
        jButton3.setActionCommand("0,5");
        jButton3.setAlignmentX(15.0F);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton4.setText("Data Kelas ");
        jButton4.setActionCommand("0,5");
        jButton4.setAlignmentX(15.0F);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton5.setText("Kehadiran");
        jButton5.setActionCommand("0,5");
        jButton5.setAlignmentX(15.0F);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton6.setText("Laporan Kehadiran");
        jButton6.setActionCommand("0,5");
        jButton6.setAlignmentX(15.0F);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton7.setText("Manajemen User");
        jButton7.setActionCommand("0,5");
        jButton7.setAlignmentX(15.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Administator");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Admin");

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton8.setText("Keluar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar?", 
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            LOGIN login = new LOGIN();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void tampilDataSiswa() {
        Connection conn = koneksi.getConnection();
        if (conn != null) {
            try {
                String sql = "SELECT s.nis, s.nama, k.nama_kelas, s.jenis_kelamin, s.alamat "
                           + "FROM siswa s LEFT JOIN kelas k ON s.kelas_id = k.id ORDER BY s.nama";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                StringBuilder sb = new StringBuilder();
                sb.append(String.format("%-12s %-25s %-10s %-5s %-30s\n", "NIS", "NAMA", "KELAS", "JK", "ALAMAT"));
                sb.append("============================================================================\n");
                while (rs.next()) {
                    sb.append(String.format("%-12s %-25s %-10s %-5s %-30s\n",
                        rs.getString("nis"),
                        rs.getString("nama"),
                        rs.getString("nama_kelas"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("alamat")));
                }
                
                javax.swing.JTextArea textArea = new javax.swing.JTextArea(sb.toString());
                textArea.setFont(new java.awt.Font("Monospaced", 0, 12));
                textArea.setEditable(false);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
                scrollPane.setPreferredSize(new java.awt.Dimension(600, 400));
                JOptionPane.showMessageDialog(this, scrollPane, "Data Siswa", JOptionPane.PLAIN_MESSAGE);
                
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void tampilDataOrangTua() {
        Connection conn = koneksi.getConnection();
        if (conn != null) {
            try {
                String sql = "SELECT s.nama AS nama_siswa, o.nama_ortu, o.no_telp, o.email "
                           + "FROM orang_tua o JOIN siswa s ON o.siswa_id = s.id ORDER BY s.nama";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                StringBuilder sb = new StringBuilder();
                sb.append(String.format("%-25s %-25s %-15s %-25s\n", "SISWA", "ORANG TUA", "NO TELP", "EMAIL"));
                sb.append("========================================================================================\n");
                while (rs.next()) {
                    sb.append(String.format("%-25s %-25s %-15s %-25s\n",
                        rs.getString("nama_siswa"),
                        rs.getString("nama_ortu"),
                        rs.getString("no_telp"),
                        rs.getString("email")));
                }
                
                javax.swing.JTextArea textArea = new javax.swing.JTextArea(sb.toString());
                textArea.setFont(new java.awt.Font("Monospaced", 0, 12));
                textArea.setEditable(false);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
                scrollPane.setPreferredSize(new java.awt.Dimension(650, 400));
                JOptionPane.showMessageDialog(this, scrollPane, "Data Orang Tua", JOptionPane.PLAIN_MESSAGE);
                
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void tampilDataKelas() {
        Connection conn = koneksi.getConnection();
        if (conn != null) {
            try {
                String sql = "SELECT k.nama_kelas, k.wali_kelas, COUNT(s.id) AS jumlah_siswa "
                           + "FROM kelas k LEFT JOIN siswa s ON k.id = s.kelas_id "
                           + "GROUP BY k.id, k.nama_kelas, k.wali_kelas ORDER BY k.nama_kelas";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                StringBuilder sb = new StringBuilder();
                sb.append(String.format("%-15s %-25s %-15s\n", "KELAS", "WALI KELAS", "JML SISWA"));
                sb.append("=========================================================\n");
                while (rs.next()) {
                    sb.append(String.format("%-15s %-25s %-15s\n",
                        rs.getString("nama_kelas"),
                        rs.getString("wali_kelas"),
                        rs.getString("jumlah_siswa")));
                }
                
                javax.swing.JTextArea textArea = new javax.swing.JTextArea(sb.toString());
                textArea.setFont(new java.awt.Font("Monospaced", 0, 12));
                textArea.setEditable(false);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
                scrollPane.setPreferredSize(new java.awt.Dimension(500, 300));
                JOptionPane.showMessageDialog(this, scrollPane, "Data Kelas", JOptionPane.PLAIN_MESSAGE);
                
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void tampilManajemenUser() {
        Connection conn = koneksi.getConnection();
        if (conn != null) {
            try {
                String sql = "SELECT username, role, created_at FROM users ORDER BY id";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                StringBuilder sb = new StringBuilder();
                sb.append(String.format("%-20s %-15s %-25s\n", "USERNAME", "ROLE", "DIBUAT"));
                sb.append("============================================================\n");
                while (rs.next()) {
                    sb.append(String.format("%-20s %-15s %-25s\n",
                        rs.getString("username"),
                        rs.getString("role"),
                        rs.getString("created_at")));
                }
                
                javax.swing.JTextArea textArea = new javax.swing.JTextArea(sb.toString());
                textArea.setFont(new java.awt.Font("Monospaced", 0, 12));
                textArea.setEditable(false);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
                scrollPane.setPreferredSize(new java.awt.Dimension(500, 300));
                JOptionPane.showMessageDialog(this, scrollPane, "Manajemen User", JOptionPane.PLAIN_MESSAGE);
                
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dsmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dsmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dsmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dsmainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dsmainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
